### ISSUE TITLE
I love your plots

### ISSUE THREAD

**Issue by loukesio** [nrennie/30DayChartChallenge#1]
Dear nrennie 

I love your plots and I was wondering if you could share from the 
https://github.com/nrennie/30DayChartChallenge/blob/main/2022/scripts/04_flora.R
the 
```
polygons <- read.csv("2022/data/voronoi.csv")
```
I am really curious how its structure looks like  

thank you for your time and thanks for sharing this great work

**Comment by nrennie** [comment]
Yes, the data set is attached here. 
[voronoi.csv](https://github.com/nrennie/30DayChartChallenge/files/8455388/voronoi.csv)

You can also recreate it by uploading the "sunflowers.csv" file on this website: [https://observablehq.com/@ladataviz/wip-voronoi-data-generator](https://observablehq.com/@ladataviz/wip-voronoi-data-generator)

**Comment by loukesio** [comment]
thank you so much!
