### ISSUE TITLE
Would you please upload your data folder?

### ISSUE THREAD

**Issue by chenghengchao** [nrennie/30DayChartChallenge#2]
Hi nrennie!
I want to learn your script but I can't find the "./2022/data" folder，it is not convenient。 Would you please upload it or share it by other ways?My email is 2511644508@qq.com. Hope for your reply!

**Comment by nrennie** [comment]
Hi, if you look at the .gitignore file you can see that I have chosen not to upload the data folder. This is for two reasons: 
- the data folder is very large (>20GB) and it is not recommended or a good idea to upload a file of this size to github
- all of the data that I used is already publicly available with sources cited in captions. I do not duplicate public data sources in general. If there is a particular source you cannot find, I can direct you to it more clearly, but "your script" doesn't tell me which one you can't find.

NB I chose to share my code even though I did not have to, and used my own personal time to do so - calling it "not convenient" is rather rude.
